/**
 * Home Page Component
 * 
 * Auto-generated by Web App Builder
 * Last modified: 2025-10-27
 */

import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Input } from '../components/ui/input';
import { Button } from '../components/ui/button';
import Custom17614079904442 from '../components/Custom17614079904442';

export default function Home({ openModal }: { openModal: (pageId: string, options?: { title?: string; closable?: boolean }) => void }) {
  const navigate = useNavigate();
  const [variable1, setVariable1] = useState("765");

  // Component styles
  const pageContainerStyle = {
    width: '1440px',
    minHeight: '1024px',
    backgroundColor: '#ffffff',
    position: 'relative',
    margin: '0 auto',
    display: 'flex',
    flexDirection: 'column',
    fontFamily: 'Inter, sans-serif'
  } as const;
  const inputStyle0 = {
      position: 'absolute',
      left: '50px',
      top: '49px',
      width: '200px',
      height: '40px'
    } as const;
  const custom-1761407990444Style1 = {
      position: 'absolute',
      left: '70px',
      top: '115px',
      width: '200px',
      height: '100px'
    } as const;
  const buttonStyle2 = {
      position: 'relative',
      left: '58px',
      top: '280px',
      width: '120px',
      height: '40px'
    } as const;
  const buttonStyle3 = {
      position: 'relative',
      left: '178px',
      top: '186.33333333333334px',
      width: '144px',
      height: '40px'
    } as const;

  return (
    <div
      id="page-1761407980108"
      style={pageContainerStyle}
    >
      <Input
        type="text"
        placeholder="Enter text..."
        value={variable1}
        onChange={(e) => setVariable1(e.target.value)}
        style={{inputStyle0}}
      />
      <Custom17614079904442 text={variable1} title="Custom Component" count={0} isActive={false} />
      <Button onClick={() => navigate('/page2')} style={{buttonStyle2}}>
        Button
      </Button>
      <Button onClick={() => openModal('page-1761489007826', { title: '', closable: true })} style={{buttonStyle3}}>
        Open in modal
      </Button>
    </div>
  );
}
