/**
 * Home Page Component
 * 
 * Auto-generated by Web App Builder
 * Last modified: 2025-10-27
 */

import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Input } from '../components/ui/input';
import { Button } from '../components/ui/button';
import Custom17614079904442 from '../components/Custom17614079904442';

export default function Home({ openModal }: { openModal: (pageId: string, options?: { title?: string; closable?: boolean }) => void }) {
  const navigate = useNavigate();
  const [variable1, setVariable1] = useState("765");

  // Component styles
  const pageContainerStyle = {
    width: '1440px',
    minHeight: '1024px',
    backgroundColor: '#ffffff',
    position: 'relative',
    margin: '0 auto',
    display: 'flex',
    flexDirection: 'column',
    fontFamily: 'Inter, sans-serif'
  } as const;
  const inputStyle0 = {
      position: 'absolute',
      left: '50px',
      top: '49px',
      width: '200px',
      height: '40px'
    } as const;
  const custom_1761407990444Style1 = {
      position: 'absolute',
      left: '50px',
      top: '115px',
      width: '200px',
      height: '100px'
    } as const;
  const flexStyle2 = {
      position: 'absolute',
      left: '50px',
      top: '258.33333333333337px',
      width: '587px',
      height: 'auto',
      flexDirection: 'row',
      gap: '8px',
      padding: '0px',
      justifyContent: 'flex-start',
      alignItems: 'flex-start',
      flexWrap: 'nowrap'
    } as const;
  const buttonStyle3 = {
      position: 'relative',
      left: '0px',
      top: '0px',
      width: '120px',
      height: '40px'
    } as const;
  const buttonStyle4 = {
      position: 'relative',
      left: '0px',
      top: '0px',
      width: '100%',
      height: '40px'
    } as const;

  return (
    <div
      id="page-1761407980108"
      style={pageContainerStyle}
    >
      <Input
        type="text"
        placeholder="Enter text..."
        value={variable1}
        onChange={(e) => setVariable1(e.target.value)}
        style={{inputStyle0}}
      />
      <Custom17614079904442 text={variable1} title="Custom Component" count={0} isActive={false} />
      <div style={{flexStyle2}}>
        <Button onClick={() => navigate('/page2')} style={{buttonStyle3}}>
          Button
        </Button>
        <Button onClick={() => openModal('page-1761489007826', { title: '', closable: true })} style={{buttonStyle4}}>
          Open in modal
        </Button>
      </div>
    </div>
  );
}
