/**
 * Home Page Component
 * 
 * Auto-generated by Web App Builder
 * Last modified: 2025-10-30
 */

import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Custom17614079904442 from '../components/Custom17614079904442';
import Custom17617334206294 from '../components/Custom17617334206294';
import Custom17614079904445 from '../components/Custom17614079904445';

import './Home.css';

export default function Home({ openModal }: { openModal: (pageId: string, options?: { title?: string; closable?: boolean }) => void }) {
  const navigate = useNavigate();
  const [variable1, setVariable1] = useState("7655");

  // Page container style
  const pageContainerStyle = {
    position: 'relative',
    margin: '0 auto',
    display: 'flex',
    fontFamily: 'Inter, sans-serif',
    flexDirection: 'column',
    gap: '16px'
  } as const;

  return (
    <div
      id="page-1761407980108"
      style={pageContainerStyle}
    >
      <input
        id="comp-1761407986406"
        type="text"
        placeholder="Enter text..."
        value={variable1}
        onChange={(e) => setVariable1(e.target.value)}
        className="home-input-comp-1761407986406"
      />
      <Custom17614079904442 text={variable1} title="Custom Component" count={0} isActive={false} />
      <div id="comp-1761564399738" className="home-flex-comp-1761564399738">
        <button id="comp-1761493557594" className="home-button-comp-1761493557594" onClick={() => navigate('/page2')}>
          Button
        </button>
        <button id="comp-1761494794693" className="home-button-comp-1761494794693" onClick={() => openModal('page-1761489007826', { title: '', closable: true })}>
          Open in modal
        </button>
      </div>
      <Custom17617334206294 />
      <Custom17614079904445 text="Hello" title="Custom Component" count={0} isActive={false} />
    </div>
  );
}
