/**
 * Page2 Page Component
 * 
 * Auto-generated by Web App Builder
 * Last modified: 2025-11-01
 */

import './Page2.css';

export default function Page2({ openModal }: { openModal: (pageId: string, options?: { title?: string; closable?: boolean }) => void }) {
  // Page container style
  const pageContainerStyle = {
    position: 'relative',
    margin: '0 auto'
  } as const;

  return (
    <div
      id="page-1761489007826"
      style={pageContainerStyle}
    >
      <div id="comp-1761489015519" className="page2-text-comp-1761489015519">
        This is Page 2
      </div>
    </div>
  );
}
