/**
 * Page2 Page Component
 * 
 * Auto-generated by Web App Builder
 * Last modified: 2025-10-26
 */

export default function Page2({ openModal }: { openModal: (pageId: string, options?: { title?: string; closable?: boolean }) => void }) {
  // Component styles
  const pageContainerStyle = {
    width: '1440px',
    minHeight: '1024px',
    backgroundColor: '#ffffff',
    position: 'relative',
    margin: '0 auto',
    display: 'flex',
    flexDirection: 'column'
  } as const;
  const textStyle0 = {
      position: 'relative',
      left: '50px',
      top: '50px',
      width: '200px',
      height: 'auto'
    } as const;

  return (
    <div
      id="page-1761489007826"
      style={pageContainerStyle}
    >
      <div style={{textStyle0}}>
        This is Page 2
      </div>
    </div>
  );
}
