/**
 * Main Application Component
 * 
 * Auto-generated by Web App Builder
 * Project: E-commerce Landing
 */

import { useState } from 'react';
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from './components/ui/dialog';
import Home from './pages/Home';
import Page2 from './pages/Page2';

function App() {
  // Global modal state management
  const [modalState, setModalState] = useState<{
    isOpen: boolean;
    pageId: string | null;
    title?: string;
    closable: boolean;
  }>({
    isOpen: false,
    pageId: null,
    title: '',
    closable: true,
  });

  // Function to open modal with a specific page
  const openModal = (pageId: string, options?: { title?: string; closable?: boolean }) => {
    setModalState({
      isOpen: true,
      pageId,
      title: options?.title || '',
      closable: options?.closable !== false,
    });
  };

  // Function to close modal
  const closeModal = () => {
    setModalState({
      isOpen: false,
      pageId: null,
      title: '',
      closable: true,
    });
  };

  return (
    <Router>
      <div className="w-full min-h-screen">
        <Routes>
        <Route path="/" element={<Home openModal={openModal} />} />
        <Route path="/page2" element={<Page2 />} />
        </Routes>
      </div>

      {/* Global Modal Dialog */}
      <Dialog 
        open={modalState.isOpen} 
        onOpenChange={(open) => {
          if (!open && modalState.closable) {
            closeModal();
          }
        }}
      >
        <DialogContent 
          className="max-w-4xl max-h-[90vh] overflow-y-auto"
          onInteractOutside={(e) => {
            if (!modalState.closable) {
              e.preventDefault();
            }
          }}
        >
          {modalState.title && (
            <DialogHeader>
              <DialogTitle>{modalState.title}</DialogTitle>
            </DialogHeader>
          )}
          <div className="mt-4">
        {modalState.pageId === 'page-1761407980108' && (
          <div style={{
          backgroundColor: '#ffffff',
          minHeight: '400px',
          width: '100%',
          position: 'relative'
        }}>
            <Home openModal={openModal} />
          </div>
        )}
        {modalState.pageId === 'page-1761489007826' && (
          <div style={{
          backgroundColor: '#ffffff',
          minHeight: '400px',
          width: '100%',
          position: 'relative'
        }}>
            <Page2 openModal={openModal} />
          </div>
        )}
          </div>
        </DialogContent>
      </Dialog>
    </Router>
  );
}

export default App;
