/**
 * Main Application Component
 * 
 * Auto-generated by Web App Builder
 * Project: E-commerce Landing
 */

import { useState } from 'react';
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import Home from './pages/Home';
import Page2 from './pages/Page2';

function App() {
  // Global modal state management
  const [modalState, setModalState] = useState<{
    isOpen: boolean;
    pageId: string | null;
    title?: string;
    closable: boolean;
  }>({
    isOpen: false,
    pageId: null,
    title: '',
    closable: true,
  });

  // Function to open modal with a specific page
  const openModal = (pageId: string, options?: { title?: string; closable?: boolean }) => {
    setModalState({
      isOpen: true,
      pageId,
      title: options?.title || '',
      closable: options?.closable !== false,
    });
  };

  // Function to close modal
  const closeModal = () => {
    setModalState({
      isOpen: false,
      pageId: null,
      title: '',
      closable: true,
    });
  };

  return (
    <Router>
      <div style={{ width: '100%', minHeight: '100vh' }}>
        <Routes>
        <Route path="/" element={<Home openModal={openModal} />} />
        <Route path="/page2" element={<Page2 />} />
        </Routes>
      </div>

      {/* Global Modal Dialog - Clean Native Implementation */}
      {modalState.isOpen && (
        <div 
          style={{
            position: 'fixed',
            inset: 0,
            backgroundColor: 'rgba(0, 0, 0, 0.5)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 9999,
          }}
          onClick={() => modalState.closable && closeModal()}
        >
          <div 
            style={{
              backgroundColor: 'white',
              borderRadius: '8px',
              padding: '24px',
              maxWidth: '900px',
              maxHeight: '90vh',
              overflow: 'auto',
              position: 'relative',
            }}
            onClick={(e) => e.stopPropagation()}
          >
            {modalState.closable && (
              <button
                onClick={closeModal}
                style={{
                  position: 'absolute',
                  top: '16px',
                  right: '16px',
                  background: 'none',
                  border: 'none',
                  fontSize: '24px',
                  cursor: 'pointer',
                  padding: '4px 8px',
                }}
              >
                ×
              </button>
            )}
            {modalState.title && (
              <h2 style={{ marginTop: 0, marginBottom: '16px' }}>
                {modalState.title}
              </h2>
            )}
            <div>
        {modalState.pageId === 'page-1761407980108' && (
          <div style={{
          backgroundColor: '#ffffff',
          minHeight: '400px',
          width: '100%',
          position: 'relative'
        }}>
            <Home openModal={openModal} />
          </div>
        )}
        {modalState.pageId === 'page-1761489007826' && (
          <div style={{
          backgroundColor: '#ffffff',
          minHeight: '400px',
          width: '100%',
          position: 'relative'
        }}>
            <Page2 openModal={openModal} />
          </div>
        )}
            </div>
          </div>
        </div>
      )}
    </Router>
  );
}

export default App;
